.TH dns_name_packet 3
.SH NAME
dns_name_packet \- extract names from DNS answer packet
.SH SYNTAX
.B #include <dns.h>

int \fBdns_name_packet\fP(stralloc* \fIout\fR,const char* \fIbuf\fR,
                    unsigned int \fIlen\fR);
.SH DESCRIPTION
dns_name_packet is a low-level component of dns_name4, designed to support
asynchronous DNS lookups. It reads a DNS packet of length \fIlen\fR from \fIbuf\fR,
extracts the first PTR record from the answer section of the packet, puts the
result into \fIout\fR, and returns 0 or -1 the same way as dns_name4.
.SH "SEE ALSO"
dns_name4(3), dns_name6(3), dns_ip4_packet(3)
