.TH buffer_fromarray 3
.SH NAME
buffer_fromarray \- initialize buffer structure from array
.SH SYNTAX
.B #include <array.h>
.B #include <buffer.h>

void \fBbuffer_fromarray\fR(buffer* \fIb\fR,array* \fIa\fR);
.SH DESCRIPTION
buffer_fromarray makes a virtual read buffer from an array.  The buffer
reading functions will be able to read until the end of the data in the
array, then signal EOF.  The buffer does not have its own buffer
space, it reuses the one in the array.

Do not touch the array until you are done with the buffer!

Reading data from the buffer will not change the stralloc.
.SH "SEE ALSO"
buffer_fromsa(3), buffer_init(3), buffer(3), buffer_frombuf(3)
