.TH buffer_seek 3
.SH NAME
buffer_seek \- remove bytes from beginning of string in buffer
.SH SYNTAX
.B #include <buffer.h>

void \fBbuffer_seek\fP(buffer* \fIb\fR,size_t \fIr\fR);
.SH DESCRIPTION
buffer_seek removes \fIr\fR bytes from the beginning of the string.
\fIr\fR must be at most the current length of the string.
.SH "SEE ALSO"
buffer_init(3), buffer_feed(3), buffer_peek(3), buffer_get(3), buffer(3)
