.TH byte_copy 3
.SH NAME
byte_copy \- copy a string
.SH SYNTAX
.B #include <byte.h>

void \fBbyte_copy\fP(char *\fIout\fR,size_t \fIlen\fR,const char *\fIin\fR);
.SH DESCRIPTION
\fIbyte_copy\fR copies \fIin\fR[0] to \fIout\fR[0], \fIin\fR[1] to
\fIout\fR[1], etc., and finally \fIin\fR[\fIlen\fR-1] to
\fIout\fR[\fIlen\fR-1].

.SH "SEE ALSO"
byte_copyr(3)
