.TH tai_approx 3
.SH NAME
tai_approx \- return double-precision approximation
.SH SYNTAX
.B #include <tai.h>

extern int \fBtai_approx\fP(const struct tai* \fIt\fR);
.SH DESCRIPTION
tai_approx returns a double-precision approximation of \fIt\fR. The result of
tai_approx is always nonnegative.
.SH "SEE ALSO"
taia_approx(3)
