.TH tai_less 3
.SH NAME
tai_less \- compare two struct tai
.SH SYNTAX
.B #include <tai.h>

extern int \fBtai_less\fP(const struct tai* \fIa\fR,
                    const struct tai* \fIb\fR);
.SH DESCRIPTION
\fBtai_less\fR returns 1 if \fIa\fR is less than \fIb\fR, 0 otherwise.
.SH "SEE ALSO"
taia_less(3)
