.TH scan_double 3
.SH NAME
scan_double \- parse a floating point number in decimal ASCII representation
.SH SYNTAX
.B #include <scan.h>

size_t \fBscan_double\fP(const char *\fIsrc\fR,double *\fIdest\fR);
.SH DESCRIPTION
scan_double parses a floating point number in decimal ASCII representation
from \fIsrc\fR and writes the result into \fIdest\fR. It returns the
number of bytes read from \fIsrc\fR.
.SH "SEE ALSO"
scan_xlong(3), scan_8long(3), fmt_ulong(3)
