.TH scan_long 3
.SH NAME
scan_long \- parse an long integer in decimal ASCII representation
.SH SYNTAX
.B #include <scan.h>

size_t \fBscan_long\fP(const char *\fIsrc\fR,long *\fIdest\fR);
.SH DESCRIPTION
scan_long parses a long integer in decimal ASCII representation
from \fIsrc\fR and writes the result into \fIdest\fR. It returns the
number of bytes read from \fIsrc\fR.
.SH "SEE ALSO"
scan_ulong(3), scan_xlong(3), scan_8long(3), fmt_long(3)
