.TH scan_xlonglong 3
.SH NAME
scan_xlonglong \- parse an unsigned long long integer in hexadecimal ASCII representation
.SH SYNTAX
.B #include <scan.h>

size_t \fBscan_xlonglong\fP(const char *\fIsrc\fR,unsigned long long* \fIdest\fR);
.SH DESCRIPTION
scan_xlonglong parses an unsigned long long integer in hexadecimal ASCII
representation from \fIsrc\fR and writes the result into \fIdest\fR. It
returns the number of bytes read from \fIsrc\fR.

scan_xlonglong understands both upper and lower case letters.

scan_xlonglong does not expect or understand a "0x" prefix.
.SH "SEE ALSO"
fmt_xlonglong(3)
