.TH str_diffn 3
.SH NAME
str_diffn \- compare two ASCIIZ strings
.SH SYNTAX
.B #include <str.h>

int \fBstr_diffn\fP(const char* \fIa\fR,const char* \fIb\fR,size_t \fIlimit\fR);
.SH DESCRIPTION
\fBstr_diffn\fR returns negative, 0, or positive, depending on whether the
string \fIa\fR[0], \fIa\fR[1], ..., \fIa\fR[n]=='\\0' is
lexicographically smaller than, equal to, or greater than the string
\fIb\fR[0], \fIb\fR[1], ..., \fIb\fR[m-1]=='\\0'.

If the strings are different, str_diffn does not read bytes past the
first difference.  The strings will be considered equal if the first
\fIlimit\fR characters match.
.SH "SEE ALSO"
strlen(3)
