.TH scan_hexdump 3
.SH NAME
scan_hexdump \- decode hexdump data
.SH SYNTAX
.B #include <libowfat/textcode.h>

size_t \fBscan_hexdump\fP(const char *\fIsrc\fR,char *\fIdest\fR,size_t* \fIdestlen\fR);

.SH DESCRIPTION
scan_hexdump decodes hexdump data from src into dest.
It will stop when it encounters any invalid input characters.
It will then write the number of decoded bytes in dest into *destlen,
and return the number of bytes decoded from src.

Note that real world hexdump data is sometimes permitted to
contain whitespace characters or new lines. This function will not allow
those and return the decoded data until then.

dest can be NULL. destlen can be NULL. dest can be src.

.SH "RETURN VALUE"
scan_hexdump returns the number of bytes successfully scanned and
processed from src.
.SH EXAMPLES
scan_hexdump("302e",buf,&i) -> return 4, i=2, buf="0."

.SH "SEE ALSO"
scan_xlong(3), scan_8long(3), fmt_ulong(3)
