.TH open_trunc 3
.SH NAME
open_trunc \- open a file for writing
.SH SYNTAX
.B #include <open.h>

int \fBopen_trunc\fP(const char *\fIfilename\fR);
.SH DESCRIPTION
open_trunc opens the file \fIfilename\fR for write-only use
and returns the file handle.  If the file exists, it will be truncated
to zero bytes length.  If it does not exist, it will be created
with mode 0644.  If there was an error opening or creating the file,
open_trunc returns -1 and sets errno accordingly.
.SH "SEE ALSO"
open(2)
