.TH iob_addfile 3
.SH NAME
iob_addfile \- add file region to I/O batch
.SH SYNTAX
.B #include <iob.h>

int \fBiob_addfile\fP(io_batch* b,int64 fd,uint64 off,uint64 n);
.SH DESCRIPTION
iob_addfile schedules \fIn\fR bytes from the file descriptor \fIfd\fR
starting at offset \fIoff\fR to be written with the I/O batch \fIb\fR.

You may not close \fIfd\fR before iob_send indicates it is done.

Use \fBiob_addfile_close\fR if you want the file descriptor to be closed
automatically by \fBiob_reset\fR.
.SH "RETURN VALUE"
Returns 1 on success, 0 on failure.
.SH "SEE ALSO"
iob_reset(3), iob_send(3), iob_addbuf(3), iob_addfile_close(3)
