.TH stralloc_copy 3
.SH NAME
stralloc_copy \- copy data into a stralloc
.SH SYNTAX
.B #include <stralloc.h>

int \fBstralloc_copy\fP(stralloc* \fIsato\fR,stralloc* \fIsafrom\fR);
.SH DESCRIPTION
stralloc_copy copies the string stored in \fIsafrom\fR into \fIsa\fR. It
is the same as
\fBstralloc_copyb\fR(&\fIsato\fR, \fIsafrom\fR.s, \fIsafrom\fR.len).
\fIsafrom\fR must already be allocated.

The data that \fIsa\fR previously contained is overwritten and truncated.

If stralloc_copy has trouble allocating memory, it returns 0.  Otherwise
it returns 1.
.SH "RETURN VALUE"
1 for success, 0 on memory allocation failure.
.SH "SEE ALSO"
stralloc_copyb(3)
