.TH taia_unpack 3
.SH NAME
taia_unpack \- convert to external TAI64NA format
.SH SYNTAX
.B #include <taia.h>

extern int \fBtaia_unpack\fP(const char* buf,struct taia* \fIt\fR);
.SH DESCRIPTION
taia_unpack converts a TAI64NA label from external TAI64NA format in
\fIbuf\fR to internal format in \fIt\fR.
.SH "SEE ALSO"
tai_unpack(3), taia_pack(3)
