.TH taia_approx 3
.SH NAME
taia_approx \- return double-precision approximation
.SH SYNTAX
.B #include <taia.h>

extern int \fBtaia_approx\fP(const struct taia* \fIt\fR);
.SH DESCRIPTION
taia_approx returns a double-precision approximation of \fIt\fR. The result of
taia_approx is always nonnegative.
.SH "SEE ALSO"
tai_approx(3)
