.TH fmt_strm_malloc 3
.SH NAME
fmt_strm_malloc \- write multiple ASCII strings
.SH SYNTAX
.B #include <stdlib.h>
.B #include <fmt.h>

char* \fBfmt_strm_malloc\fP(const char *\fIsource\fR, ...);
.SH DESCRIPTION
fmt_strm_malloc copies all leading nonzero bytes from \fIsource\fR and
following function arguments to a freshly allocated heap buffer and
returns a pointer to it.

The buffer was allocated with \fImalloc\fR and you need to call
\fIfree\fR on it when you are done.

Unlink fmt_strm, fmt_strm_malloc does append \\0.

.SH "SEE ALSO"
fmt_str(3), fmt_strm(3), fmt_strm_alloca(3), alloca(3), strcpy(3)
