.TH case_lowerb 3
.SH NAME
case_lowerb \- compare strings case-insensitively
.SH SYNTAX
.B #include <case.h>

void \fBcase_lowerb\fP(void* \fIs\fR,size_t \fIlen\fR);
.SH DESCRIPTION
case_lowerb converts each 'A' to 'a', 'B' to 'b', ..., 'Z' to 'z' in
\fIs\fR[0], \fIs\fR[1], ..., \fIs\fR[\fIlen\fR].
.SH "SEE ALSO"
case_lowerb(3)
