.TH stralloc_chop 3
.SH NAME
stralloc_chop \- remove and return last char
.SH SYNTAX
.B #include <stralloc.h>

int \fBstralloc_chop\fP(stralloc* \fIsa\fR);
.SH DESCRIPTION
stralloc_chop removes the last char in the stralloc (if it is empty,
stralloc_chop does nothing and returns -1).  This character is cast to
unsigned char and returned.
.SH "RETURN VALUE"
chopped character, or -1 if string was empty.
.SH "SEE ALSO"
stralloc_chomp(3)
