.TH array_start 3
.SH NAME
array_start \- get pointer to first element in array
.SH SYNTAX
.B #include <array.h>

void* \fBarray_start\fP(array* \fIx\fR);

  array \fIx\fR;
  \fIt\fR* \fIp\fR = array_start(&\fIx\fR);

.SH DESCRIPTION
array_start is the same as array_get with \fIpos\fR equal to 0.

.SH "SEE ALSO"
array_allocate(3), array_get(3), array_fail(3)
