.TH dns_ip6_packet 3
.SH NAME
dns_ip6_packet \- extract IPv6 address from DNS answer packet
.SH SYNTAX
.B #include <dns.h>

int \fBdns_ip6_packet\fP(stralloc* \fIout\fR,const char* \fIbuf\fR,
                   unsigned int \fIlen\fR);
.SH DESCRIPTION
dns_ip6_packet is a low-level component of dns_ip6, designed to support
asynchronous DNS lookups. It reads a DNS packet of length \fIlen\fR from
\fIbuf\fR, extracts IPv4 and IPv6 addresses from the answer section of
the packet, puts the addresses into \fIout\fR, and returns 0 or -1 the
same way as dns_ip6.
.SH "SEE ALSO"
dns_ip6(3), dns_ip4_packet(3)
