.TH fmt_ip4 3
.SH NAME
fmt_ip4 \- write a formatted ASCII representation of an IPv4 number
.SH SYNTAX
.B #include <ip4.h>

unsigned int \fBfmt_ip4\fP(char *\fIdest\fR,const char \fIip\fR[4]);
.SH DESCRIPTION
fmt_ip4 formats an IPv4 number in dotted-decimal ASCII representation
from \fIip\fR and writes the result into \fIdest\fR. It returns the
number of bytes written.

If \fIdest\fR equals FMT_LEN (i.e. is zero), fmt_ip4 returns the number
of bytes it would have written.

fmt_ip4 does not append \\0.

For convenience, ip4.h defines the integer IP4_FMT to be big enough to
contain every possible fmt_ip4 output plus \\0.
.SH EXAMPLE
#include <ip4.h>

  char buf[IP4_FMT];
  char ip[4];
  buf[fmt_ip4(buf,ip)]=0;
.SH "SEE ALSO"
scan_ip4(3), fmt_ip6(3), inet_ntop(3)
