.TH socket_bind4_reuse 3
.SH NAME
socket_bind4_reuse \- set the local IP address and port of a socket
.SH SYNTAX
.B #include <socket.h>

int \fBsocket_bind4_reuse\fP(int \fIs\fR,char \fIip\fR[4],uint16 \fIport\fR);
.SH DESCRIPTION
socket_bind4_reuse sets the local IP address and TCP/UDP port of a
TCP/UDP socket \fIs\fR to \fIip\fR and \fIport\fR respectively.

If the IP address is 0.0.0.0, the operating system chooses a local IP
address.  If \fIport\fR is 0, the operating system chooses a port.

Normally socket_bind4_reuse returns 0. If anything goes wrong,
socket_bind4_reuse returns -1, setting errno appropriately.

Unlike socket_bind4 this function will also tell the operating system
that the address is to be reused soon, which turns off the normal pause
before this IP and port can be bound again.
.SH EXAMPLE
  #include <socket.h>

  int \fIs\fR;
  char \fIip\fR[4];
  uint16 \fIp\fR;

  \fIs\fR = socket_tcp4();
  socket_bind4_reuse(s,ip,p);
  socket_connect4(s,ip,p);

.SH "SEE ALSO"
socket_bind6(3)
