.TH socket_mcjoin6 3
.SH NAME
socket_mcjoin6 \- join a multicast group
.SH SYNTAX
.B #include <socket.h>

int \fBsocket_mcjoin6\fP(int \fIs\fR,const char \fIgroupip\fR[16],uint32 \fIinterface\fR);
.SH DESCRIPTION
socket_mcjoin6 joins the IPv6 multicast group \fIgroupip\fR on \fIinterface\fR.

If something goes wrong, socket_mcjoin6 returns -1, setting errno
appropriately.
.SH "SEE ALSO"
socket_mcleave6(3), socket_mcjoin4(3), socket_getifidx(3)
