.TH array_cats 3
.SH NAME
array_cats \- append C string to an array
.SH SYNTAX
.B #include <array.h>

void \fBarray_cats\fP(array* \fIx\fR,const char* \fIy\fR);

  array \fIx\fR;
  array_cats(&\fIx\fR,"fnord");

.SH DESCRIPTION
array_cats appends the contents of the 0-terminated string \fIy\fR, not
including the terminating 0 byte, to the array \fIx\fR.

array_cats handles failure in the same way as array_cat.
.SH "SEE ALSO"
array_allocate(3), array_get(3), array_fail(3), array_reset(3),
array_cat(3), array_catb(3), array_cats0(3), array_cate(3),
array_cat0(3)
