.TH msg 3
.SH NAME
msg \- print diagnostic
.SH SYNTAX
.B #include <libowfat/errmsg.h>

void \fBmsg\fP(const char *\fImessage\fR, ...);
.SH DESCRIPTION

\fImsgsys\fP is like \fImsg\fP, but it will also print a string
representation of the system error code (from errno).

.SH "SEE ALSO"
errmsg(7), msg(3)
