.TH range_strinbuf 3
.SH NAME
range_strinbuf \- range check for string in buffer
.SH SYNTAX
.B #include <rangecheck.h>

int \fBrange_strinbuf\fP(const void* buf,size_t len,const void* stringstart);
.SH DESCRIPTION
range_strinbuf checks that the ASCIIZ-string starting at
\fIstringstart\fR starts and ends within the buffer
\fIbuf\fR[0..\fIlen\fR-1].

If the string is not 0-terminated but the length is known beforehand,
use range_arrayinbuf instead.
.SH "RETURN VALUE"
If the buffer is implausible (buf is NULL or buf+len has an integer overflow), return 0.

If \fIstringstart\fR points before or after the buffer, return 0.

If there is no '\\0' within the buffer, return 0.

Otherwise, return 1.
.SH "SEE ALSO"
rangecheck(3)
