.TH buffer_frombuf 3
.SH NAME
buffer_frombuf \- initialize buffer structure from raw memory
.SH SYNTAX
.B #include <buffer.h>

void \fBbuffer_frombuf\fR(buffer* \fIb\fR,const char* \fIx\fR, size_t \fIl\fR);
.SH DESCRIPTION
buffer_frombuf makes a virtual read buffer from a raw memory area.  The buffer
reading functions will be able to read until the end of the data in the
memory area, then signal EOF.  The buffer does not have its own buffer
space, it reuses the one passed into this function.

Do not touch this memory until you are done with the buffer!

Reading data from the buffer will not change the memory you passed in.
.SH "SEE ALSO"
buffer_fromsa(3), buffer_init(3), buffer(3), buffer_frombuf(3)
