.TH buffer_getnewline_sa 3
.SH NAME
buffer_getnewline_sa \- read line from buffer
.SH SYNTAX
.nf
.B #include <stralloc.h>
.B #include <buffer.h>

int \fBbuffer_getnewline_sa\fP(buffer* \fIb\fR,stralloc* \fIsa\fR);
.SH DESCRIPTION
buffer_getnewline_sa copies data from the \fIb\fR to \fIsa\fR until a '\\n'
is found, overwriting the previous content of \fIsa\fR.  The new-line
is also appended to \fIsa\fR.

If reading from the buffer or allocating memory fails,
buffer_getnewline_sa returns -1 and sets \fIerrno\fR appropriately.  At
that point \fIsa\fR may be empty or it may already contain a partial
token.

To read from a non-blocking socket, use buffer_getline_sa.
.SH "RETURN VALUE"
-1 on error (setting errno), 0 on EOF, 1 when successful.
.SH "SEE ALSO"
buffer_get_token_sa(3), buffer(3)
