.TH carp 3
.SH NAME
carp \- print warning diagnostic
.SH SYNTAX
.B #include <errmsg.h>

void \fBcarp\fP(const char *\fImessage\fR, ...);
.SH DESCRIPTION

If \fIerrmsg_iam\fP was called to set the program name, \fIcarp\fP will
first print that program name and a colon.

\fIcarp\fP will print all its arguments to stderr (fd #2).

It does not synchronize with any other output method.

If you have unflushed data in \fIbuffer_2\fP, it will stay there.

.SH "SEE ALSO"
errmsg(7), buffer_flush(3)
