.TH die 3
.SH NAME
die \- print warning diagnostic and abort program
.SH SYNTAX
.B #include <libowfat/errmsg.h>

void \fBdie\fP(int \fIexitcode\fP, const char *\fImessage\fR, ...);
.SH DESCRIPTION

If \fIerrmsg_iam\fP was called to set the program name, \fIdie\fP will
first print that program name and a colon.

\fIdie\fP will print all its arguments to stderr (fd #2) and then call
\fIexit\fP(\fIexitcode\fP).

It does not synchronize with any other output method.

Flush \fIbuffer_1\fP and \fIbuffer_2\fP manually first if needed.

.SH NOTE

This function does not return.

.SH "SEE ALSO"
errmsg(7), buffer_flush(3)
