.TH errmsg_iam 3
.SH NAME
errmsg_iam \- tell errmsg library the name of the program
.SH SYNTAX
.B #include <libowfat/errmsg.h>

void \fBerrmsg_iam\fP(const char *\fIprogname\fR);
.SH DESCRIPTION

Use this function to set the program name.

This function is usually called directly at the start of main() and
given argv[0] as argument.

This is important for batch processing, so the observer can tell which
program the error message came from.

.SH "SEE ALSO"
errmsg(7)
