.TH open_read 3
.SH NAME
open_read \- open a file for reading
.SH SYNTAX
.B #include <open.h>

int \fBopen_read\fP(const char *\fIfilename\fR);
.SH DESCRIPTION
open_read opens the file \fIfilename\fR for reading and returns the file
handle.  If there was an error opening the file, open_read returns -1
and sets errno accordingly.
.SH "SEE ALSO"
open(2)
