.TH fmt_ulong0 3
.SH NAME
fmt_ulong0 \- write a zero-padded ASCII representation of an unsigned long integer
.SH SYNTAX
.B #include <fmt.h>

size_t \fBfmt_ulong0\fP(char *\fIdest\fR, unsigned long \fIsource\fR,
                        size_t \fIn\fR);
.SH DESCRIPTION
fmt_ulong0 writes an ASCII representation ('0' to '9', base 10) of
\fIsource\fR to \fIdest\fR and returns the number of bytes written.
The output is padded with '0'-bytes until it encompasses at least
\fIn\fR bytes, but it will not be truncated if it does not fit.

fmt_ulong0 does not append \\0.

If \fIdest\fR equals FMT_LEN (i.e. is zero), fmt_ulong0 returns the number
of bytes it would have written.

For convenience, fmt.h defines the integer FMT_ULONG to be big enough to
contain every possible fmt_ulong output plus \\0.
.SH "SEE ALSO"
scan_ulong(3), fmt_ulong(3)
