.TH fmt_uint 3
.SH NAME
fmt_uint \- write an ASCII representation of an unsigned integer
.SH SYNTAX
.B #include <fmt.h>

size_t \fBfmt_uint\fP(char *\fIdest\fR,unsigned int \fIsource\fR);
.SH DESCRIPTION
fmt_uint writes an ASCII representation ('0' to '9', base 10) of
\fIsource\fR to \fIdest\fR and returns the number of bytes written.

fmt_uint does not append \\0.

If \fIdest\fR equals FMT_LEN (i.e. is zero), fmt_uint returns the number
of bytes it would have written.

For convenience, fmt.h defines the integer FMT_ULONG to be big enough to
contain every possible fmt_uint output plus \\0.
.SH "SEE ALSO"
scan_uint(3), fmt_uint0(3)
